name: Test VPP Build

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        sudo add-apt-repository universe multiverse
        sudo apt update
        git clone https://gerrit.fd.io/r/vpp
        cd vpp
        export UNATTENDED=yes
        make install-dep pkg-deb pkg-deb-debug
        # docker build . --file Dockerfile --tag my-image-name:$(date +%s)
