name: Test VPP Build

on:
  schedule:
  - cron:  '15 1 * * *'

#  - cron:  '0 5 * * *'
  
# - push


jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        sudo apt-get install -y --allow-downgrades libllvm6.0=1:6.0-1ubuntu2
        sudo apt-get install clang-format-6.0
        sudo apt-get update
        git clone https://gerrit.fd.io/r/vpp
        cd vpp
        export UNATTENDED=yes
        make install-dep pkg-deb
        # pkg-deb-debug

    - name: Publish the build to docker
      env:
         DOCKER_CONFIG_JSON: ${{ secrets.DOCKER_CONFIG_JSON}}
      run: |
        mkdir ~/.docker
        echo ${DOCKER_CONFIG_JSON} >~/.docker/config.json
        cd vpp
        TAG="vpp-docker-nodebug:$(date +'%Y%m%d')"
        docker build . --no-cache --file ../Dockerfile --tag ayourtch/${TAG}
        docker push ayourtch/${TAG}
        
        
